###
http://localhost:5000

### get all role
http://localhost:5000/roles

### create roles
POST http://localhost:5000/roles
Content-Type: application/json

{
    "role": "audience"
}

### get one role by id
GET http://localhost:5000/roles/7a6401b1-0d62-4c99-aa18-909682190e91

### update role by id
PUT http://localhost:5000/roles/7a6401b1-0d62-4c99-aa18-909682190e91
Content-Type: application/json

{
    "role": "audience"
}

### delete role by id
DELETE http://localhost:5000/roles/12

### get all users
GET http://localhost:5000/users

### get user by id
GET http://localhost:5000/users/9214ebc5-cb65-4acb-8e48-2b3e3ce4d324

### delete user by id
DELETE http://localhost:5000/users/9214ebc5-cb65-4acb-8e48-2b3e3ce4d321

### register user
POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "role_id": "7641ac4d-4abe-4b19-b824-8c9abda77e62", 
    "email": "akmaliatrias13@yahoo.com",
    "username": "akmaliatrias22", 
    "password": "123", 
    "avatar": "photo.jpg"
}

### login user
POST http://localhost:5000/auth/login
Content-Type: application/json

{
    "email": "akmaliatrias13@yahoo.com", 
    "password": "123"
}

### authorize-token
GET http://localhost:5000/auth/authorize-token
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFrbWFsaWF0cmlhczEzQHlhaG9vLmNvbSIsInN1YiI6IjQ4OTk5ZmYzLWJjY2ItNDI3ZS04MGVhLTY4NjUwYTYzZmZhZSIsImlhdCI6MTczMjA3NzIzOCwiZXhwIjoxNzMyMTYzNjM4fQ.iCp5ob9Dl0trJlSQu39164AaEbKbkorO4m9C5wTWEuO

### create crews
POST http://localhost:5000/crews
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFrbWFsaWF0cmlhczEzQHlhaG9vLmNvbSIsInN1YiI6IjQ4OTk5ZmYzLWJjY2ItNDI3ZS04MGVhLTY4NjUwYTYzZmZhZSIsImlhdCI6MTczMjE3MTk1NiwiZXhwIjoxNzMyMjU4MzU2fQ.DQu56yGI30mAL49tVcq7axuLjgHEU7CWdtivMZ18XIQ

{ 
    "name": "Hayao Miyazaki",
    "birthday": "1941-01-05",
    "birthplace": "Tokyo, Japan",
    "biography": "Hayao Miyazaki is a legendary Japanese animator, director, and co-founder of Studio Ghibli. His works, including Spirited Away, My Neighbor Totoro, and Princess Mononoke, are celebrated for their breathtaking animation, rich storytelling, and environmental themes.",
    "photos": []
}

### get all crews
GET http://localhost:5000/crews
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFrbWFsaWF0cmlhczEzQHlhaG9vLmNvbSIsInN1YiI6IjQ4OTk5ZmYzLWJjY2ItNDI3ZS04MGVhLTY4NjUwYTYzZmZhZSIsImlhdCI6MTczMjE3MTk1NiwiZXhwIjoxNzMyMjU4MzU2fQ.DQu56yGI30mAL49tVcq7axuLjgHEU7CWdtivMZ18XIQ


## get one crews by id
GET http://localhost:5000/crews/1821610c-b9a9-4315-b718-bc1110b19372

### update crew by id 
PUT http://localhost:5000/crews/1821610c-b9a9-4315-b718-bc1110b19372
Content-Type: application/json

{
    "name": "Akmalia Siapa Astaga", 
    "birthday": "1979-11-02", 
    "birthplace": "Palo Alto, California, USA", 
    "biography": "Jon M. Chu attended the USC School of Cinematic Arts and his talents were immediately recognized. He won a number of awards for his short film work--the musicals Silent Beats and When the Kids Are Away--such as the Jack Nicholson Directing Award, the Kodak Student Filmmaker Award, and the Princess Grace Award, among others. His work on When the Kids Are Away an energetic and humorous musical about what mothers really get up to when their kids are out of the house, nabbed Chu representation at the William Morris Agency and the possibility of Hollywood success was at his fingertips", 
    "photos": [
        {"photo": "photo12.jpg"},
        {"photo": "photo22.jpg"},
        {"photo": "photo32.jpg"}
    ]
}

### delete by id
DELETE http://localhost:5000/crews/d4dde888-e468-4bdf-8625-be4853cb5829

### create movie 
POST http://localhost:5000/movies-s
Content-Type: application/json

{
    "": "TV/Sitkom"
}

### get all movie 
GET http://localhost:5000/movies-s

### get one movie  by id
GET http://localhost:5000/movies-s/2b79799e-3e6e-443c-8f17-af9259999477

### update movie  by id
PUT http://localhost:5000/movies-s/2b79799e-3e6e-443c-8f17-af9259999477
Content-Type: application/json

{
    "": "TV"
}

### delete movie  by id
DELETE http://localhost:5000/movies-s/2b79799e-3e6e-443c-8f17-af9259999477

### create crew position
POST http://localhost:5000/crews-positions
Content-Type: application/json

{
    "position": "Producer"
}

### get all crew position
GET http://localhost:5000/crews-positions

### get one crew position by id
GET http://localhost:5000/crews-positions/cf3897ef-5abf-4f3f-9f71-2aefd5e3920a

### update crew position by id
PUT http://localhost:5000/crews-positions/cf3897ef-5abf-4f3f-9f71-2aefd5e3920a
Content-Type: application/json

{
    "position": "Script Writer"
}

### delete crew position by id
DELETE http://localhost:5000/crews-positions/cf3897ef-5abf-4f3f-9f71-2aefd5e3920a

### create movies
POST http://localhost:5000/movies
Content-Type: application/json

{
    "movie_type_id": "ab2c54c9-b1d3-4b3f-a399-d26d85ca4358",
    "title": "The Batman",
    "synopsis": "Bruce Wayne faces the Riddler, a mysterious criminal targeting Gotham's elite, while uncovering secrets about his family's past.",
    "distributor": "Warner Bros. Pictures",
    "rating": "PG-13 (Violence|Dark Themes)",
    "production_co": "DC Films, 6th & Idaho Productions",
    "original_lang": "English",
    "release_date_theather": "2022-03-04",
    "release_date_streaming": "2022-05-18",
    "runtime": "02:56:00",
    "soundmix": "Dolby Atmos",
    "moviesGenres": [
        {"genre_id": "e1417639-d61f-47ec-b89f-f82436ef8f4c"}, 
        {"genre_id": "187d98de-6223-428d-87cf-22f8fd3797a4"}, 
        {"genre_id": "85e6a1a8-b598-4ed8-a8a4-774dea0c2db0"}, 
        {"genre_id": "1bde8853-0adf-4ab2-a582-f4c87eb98dd3"}
    ],
    "moviesPostres": [
        {"poster": "poster1.jpg"},
        {"poster": "poster2.jpg"},
        {"poster": "poster3.jpg"}
    ],
    "moviesCrewPosition":[
        {
            "crew_id": "4b7552b3-3bb6-44c9-bef9-c91fbd3940cc", 
            "position_id": "47684fd5-1eaf-4bf2-b4bb-e51e0a530264"
        }, 
        {
            "crew_id": "4b7552b3-3bb6-44c9-bef9-c91fbd3940cc", 
            "position_id": "4a9ce556-073a-442e-8ed8-898d7bae5a03"
        }
    ]
}

### get genre
GET http://localhost:5000/genres

## get crew 
GET http://localhost:5000/crews
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFrbWFsaWF0cmlhczEzQHlhaG9vLmNvbSIsInN1YiI6IjQ4OTk5ZmYzLWJjY2ItNDI3ZS04MGVhLTY4NjUwYTYzZmZhZSIsImlhdCI6MTczMjE3MTk1NiwiZXhwIjoxNzMyMjU4MzU2fQ.DQu56yGI30mAL49tVcq7axuLjgHEU7CWdtivMZ18XIQ

## get positions
POST http://localhost:5000/crews-positions
Content-Type: application/json

{
    "position": "Sound Designer"
}


### create movie 
POST http://localhost:5000/genres
Content-Type: application/json

{ "genre": "Sci-Fi" }

### get all movie genre
GET http://localhost:5000/genres

### get one movie genre by id
GET http://localhost:5000/genres/2b79799e-3e6e-443c-8f17-af9259999477

### update movie genre by id
PUT http://localhost:5000/genres/2b79799e-3e6e-443c-8f17-af9259999477
Content-Type: application/json

{
    "genre": "TV"
}

### delete movie genre by id
DELETE http://localhost:5000/genres/2b79799e-3e6e-443c-8f17-af9259999477

